temp_db = {
    'Active':               {'stat': 'agility',     'modifier': +5},
    'Adaptable':            {'stat': 'cunning',     'modifier': +5},
    'Adventurous':          {'stat': 'agility',     'modifier': +5},
    'Affectionate':         {'stat': 'charm',       'modifier': +5},
    'Agile':                {'stat': 'agility',     'modifier': 0},
    'Alert':                {'stat': 'defense',     'modifier': 0},
    'Calm':                 {'stat': 'cunning',     'modifier': 0},
    'Clever':               {'stat': 'cunning',     'modifier': 0},
    'Curious':              {'stat': 'defense',     'modifier': -5},
    'Demanding':            {'stat': 'charm',       'modifier': -5},
    'Dependent':            {'stat': 'cunning',     'modifier': 0},
    'Devoted':              {'stat': 'charm',       'modifier': 0},
    'Easy going':           {'stat': 'charm',       'modifier': 0},
    'Easygoing':            {'stat': 'charm',       'modifier': 0},
    'Energetic':            {'stat': 'agility',     'modifier': 0},
    'Expressive':           {'stat': 'charm',       'modifier': 0},
    'Friendly':             {'stat': 'charm',       'modifier': 0},
    'Fun-loving':           {'stat': 'charm',       'modifier': 0},
    'Gentle':               {'stat': 'charm',       'modifier': 0},
    'Highly intelligent':   {'stat': 'cunning',     'modifier': 0},
    'Highly interactive':   {'stat': 'agility',     'modifier': 0},
    'Independent':          {'stat': 'cunning',     'modifier': 0},
    'Inquisitive':          {'stat': 'cunning',     'modifier': 0},
    'Intelligent':          {'stat': 'cunning',     'modifier': 0},
    'Interactive':          {'stat': 'agility',     'modifier': 0},
    'Lively':               {'stat': 'agility',     'modifier': 0},
    'Loving':               {'stat': 'charm',       'modifier': 0},
    'Loyal':                {'stat': 'charm',       'modifier': 0},
    'Mischievous':          {'stat': 'cunning',     'modifier': -5},
    'Outgoing':             {'stat': 'charm',       'modifier': 0},
    'Patient':              {'stat': 'cunning',     'modifier': 0},
    'Peaceful':             {'stat': 'charm',       'modifier': 0},
    'Playful':              {'stat': 'agility',     'modifier': 0},
    'Quiet':                {'stat': 'charm',       'modifier': 0},
    'Relaxed':              {'stat': 'defense',     'modifier': -5},
    'Sedate':               {'stat': 'defense',     'modifier': -5},
    'Sensible':             {'stat': 'cunning',     'modifier': 0},
    'Sensitive':            {'stat': 'charm',       'modifier': -5},
    'Shy':                  {'stat': 'charm',       'modifier': -5},
    'Sociable':             {'stat': 'charm',       'modifier': 0},
    'Social':               {'stat': 'charm',       'modifier': 0},
    'Sweet':                {'stat': 'charm',       'modifier': 0},
    'Sweet-tempered':       {'stat': 'charm',       'modifier': 0},
    'Talkative':            {'stat': 'charm',       'modifier': 0},
    'Tenacious':            {'stat': 'strength',    'modifier': 0},
    'Trainable':            {'stat': 'strength',    'modifier': 0},
    'Warm':                 {'stat': 'charm',       'modifier': 0},
}